name: audio_handler
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.9
  just_audio: ^0.9.31
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:































